### ISSUE TITLE
Membership : daftar member

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#1]
Saat ini belum bisa melihat daftar member. 

Thanks.

**Comment by AbuMuhammad** [comment]
Daftar member bisa dilihat di Config -> Profil, 
Di sana akan tampil semua profil: supplier, customer, karyawan.
Kemudian filter berdasarkan tipe: pilih customer. Customer yang ada nomor adalah member. Untuk mencari nomor terakhir, bisa diklik headernya untuk sorting
