### ISSUE TITLE
FR : fasilitas search barang di form Input Pembelian

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#11]
FR (feature request)

Mohon agar ada fitur Search Barang di form Input Pembelian.

Jadi bisa search secara bebas (bukan hanya berurut sesuai barcode atau huruf-huruf awal nama barang tsb)

Mungkin berupa tombol yang kemudian memunculkan popup ? seperti tombol "Tambah Barang"

Terimakasih.

![screenshot from 2016-08-12 10-38-29](https://cloud.githubusercontent.com/assets/170206/17612166/0f344448-6079-11e6-87bb-648ad884d17b.png)

**Comment by AbuMuhammad** [comment]
Baik pak,
Ada beberapa pertanyaan terkait.
Carinya tetap untuk barang supplier tersebut atau "bebas" maksudnya semua
data barang yg ada (di luar supplier tersebut)?

Untuk dropdown sepertinya akan tetap ada, akan tetapi bisa diubah di menu
config untuk pilihan inputnya (apakah dropdown atau cari).

Oh ya, fitur cari nya apakah seperti di pos (muncul table) atau seperti
input diskon (autocomplete)?

FYI: Halaman POS saat ini sudah ada pilihan untuk cari barang, apakah
muncul tabel atau autocomplete.

**Comment by sufehmi** [comment]
> Carinya tetap untuk barang supplier tersebut atau "bebas" maksudnya semua
data barang yg ada (di luar supplier tersebut)?

Hanya boleh untuk supplier tsb.

> Untuk dropdown sepertinya akan tetap ada, akan tetapi bisa diubah di menu
config untuk pilihan inputnya (apakah dropdown atau cari).

Tolong ada dua-duanya saja.

> Oh ya, fitur cari nya apakah seperti di pos (muncul table) atau seperti
input diskon (autocomplete)?

Tolong table saja, agar lebih rendah pemakaian memory nya & mudah-mudahan lebih kompatibel dengan berbagai perangkat / gadget.

Terimakasih.

**Comment by AbuMuhammad** [comment]
Selesai.
3 pilihan jenis input, bisa dipilih di Config -> Application -> pembelian.caribarangmode

Auto Complete
![pembelian-input-autocomplete](https://cloud.githubusercontent.com/assets/3438768/17740849/3ed8b1ee-64c4-11e6-918b-4244078028d7.png)


Tabel
![pembelian-input-tabel](https://cloud.githubusercontent.com/assets/3438768/17741228/9a11254a-64c5-11e6-937a-0048d26ad225.png)


Double Dropdown (seperti ahadpos2)
![pembelian-input-doubledropdown](https://cloud.githubusercontent.com/assets/3438768/17741234/a4189f8c-64c5-11e6-9d93-58e0dd36a5a4.png)

**Comment by sufehmi** [comment]
Pak, mohon agar bisa dua-duanya (dropdown box & search), bukan jadi opsi salah satu. Seperti saya request disini : https://github.com/AbuMuhammad/ap3/issues/11#issuecomment-239437243

Terimakasih.

**Comment by sufehmi** [comment]
Tampilkan saja di sebelah kanan dropdown box, masih cukup lapang space horizontal di baris tsb.

Terimakasih.

**Comment by AbuMuhammad** [comment]
Saya belum mengerti pak :senyum.
Fungsi fitur search tersebut. Apakah pilih barang untuk diinput pembelian (seperti yang sudah dibuat di atas) atau hanya menampilkan info barang tersebut?

Space disebelah kanan dropdown box adalah untuk input pembeliannya pak. Yang akan muncul ketika barang sudah dipilih
![pembelian-input](https://cloud.githubusercontent.com/assets/3438768/17768275/7d594232-655d-11e6-8f53-d5c2a7163e4f.png)

**Comment by sufehmi** [comment]
Duh ini kelewatan sama saya 🙏

Iya pak, ini agar bisa search =nama= barang dengan lebih fleksibel, tidak musti sesuai urutan huruf dari depan

Baik pak, nampaknya yang "tabel" sudah seperti yang diminta ya?
Bagaimana baiknya ya? Apakah dropdown "nama" diganti dengan itu saja?

Terimakasih

**Comment by AbuMuhammad** [comment]
Iya, pakai tabel bisa. Dan itu bisa diubah lewat settingan.
Dropdown nama meneruskan "tradisi" ahadPOS2. Kalau diganti bisa lewat config
![screenshot_20171014_153739](https://user-images.githubusercontent.com/3438768/31574257-e06fc7c6-b0f5-11e7-93fe-1ee087a280f9.png)
