### ISSUE TITLE
Error saat menjalankan fresh-install.sh

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#12]
Muncul pesan sbb : 

```
sufehmi@HSZ ~/D/P/P/a/a/ap3> ./fresh-install.sh 

Failed to execute process './fresh-install.sh'. Reason:
exec: Exec format error
The file './fresh-install.sh' is marked as an executable but could not be run by the operating system.
```

**SOLUSI** : sisipkan baris sbb di baris nomor 1 : 

---
#!/bin/bash
---

Terimakasih.

**Comment by AbuMuhammad** [comment]
Sudah ditambahkan
[commit/6745e6a97ed799028c7eaff085445860c4399890](https://github.com/AbuMuhammad/ap3/commit/6745e6a97ed799028c7eaff085445860c4399890)
