### ISSUE TITLE
FR : Algoritma analisa "average daily stock"

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#14]
Sering kasus di berbagai toko yaitu kehabisan stok barang. 

Akibatnya adalah "lost sales" 

Yaitu penjualan yang seharusnya terjadi, namun gagal, karena kita tidak memiliki stok nya.
# 

Untuk menghindari ini, saya berencana untuk membuat "Notifikasi Potensi Lost Sales" (NPLS) di frontpage AhadPOS3
# 

Agar NLS bisa dieksekusi dengan cepat / tidak membuat lambat frontpage, maka kita perlu lakukan proses analisa "average daily stock" (ADS) secara terpisah. Dan lalu hasilnya di simpan ke sebuah table.
# 

Sebelum itu, kita musti sepakati dulu algoritma ADS. Maka kemudian baru bisa kita develop fitur NPLS ini.

Saya akan posting algoritma usulan saya di komentar berikutnya.
# 

RUJUKAN : 

(1) Tentang lost sales : http://www.evancarmichael.com/library/will-atkinson/The-Cost-of-Lost-Sales.html

(2) Standar dalam bisnis Retail adalah **mencatat** & melacak lost sales : 

http://www.counterman.com/posting-lost-sales-is-your-store-losing-business/

http://www.driveyoursuccess.com/2010/07/supply-chain-management-costs-to-inventory-of-lost-sales.html

(3) Paper tentang lost sales : http://www.cluteinstitute.com/ojs/index.php/JBER/article/download/2942/2990

**Comment by sufehmi** [comment]
```
INSERT INTO tmp(tanggal, barcode, hargaBeli, stoksaatini, ADS)

	SELECT
		NOW(),
		barcode,
		hargaBeli,
		stok,
		total/{$range} AS rata
                          
	FROM (

		SELECT b.barcode, b.namaBarang, b.jumBarang as stok, t2.hargaBeli, 
			(SELECT  IFNULL(SUM(jumBarang),0)
				FROM detail_jual AS dj
				JOIN transaksijual AS tj ON tj.idTransaksiJual = dj.nomorStruk
				WHERE barcode=b.barcode AND tj.tglTransaksiJual BETWEEN DATE_SUB(NOW(), INTERVAL {$range} DAY) AND NOW()) 
			AS total
                                  
		FROM barang b

		LEFT JOIN (

			SELECT db . *
			FROM detail_beli AS db
			JOIN 	(
				SELECT barcode, MAX( idTransaksiBeli ) AS idTransaksiBeli
				FROM detail_beli GROUP BY barcode
				)
			AS t1 ON t1.barcode = db.barcode AND t1.idTransaksiBeli = db.idTransaksiBeli
		)
		AS t2 ON t2.barcode = b.barcode
                          
		WHERE b.idSupplier ={$supplierid}

	) AS t3;
```

**Comment by sufehmi** [comment]
Rujukan : http://localhost/ahadpos2/sistem/media.php?module=pembelian_barang&act=rposup2

**Comment by AbuMuhammad** [comment]
Sudah selesai
