### ISSUE TITLE
FR : Notifikasi Potensi Lost Sales (NPLS) 

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#15]
Berdasarkan algoritma ADS (average daily sales) disini : [https://github.com/AbuMuhammad/ap3/issues/14](https://github.com/AbuMuhammad/ap3/issues/14)

Mohon agar bisa dibuatkan fitur NPLS yang ditampilkan di frontpage. 
# 

Alurnya sbb : 
1. Sebuah script, bisa dijalankan via cron
2. Menjalankan algoritma ADS, dan menyimpan ke sebuah tabel, rekap_ads
3. Di frontpage AhadPOS, query rekap_ads sbb : 

$periode_supplier = 7; // hari

SELECT ads.barcode, b.namaBarang, ads.stok, ads.ADS, (ads.stok \* ads.ADS) AS sisahari  
FROM rekap_ads AS ads, barang AS b 
WHERE b.barcode = ads.barcode AND (stok < (ADS \* $periode_supplier)) 
GROUP BY b.idSupplier 
ORDER BY sisahari.ADS DESC ; 

4.Tampilkan di sebuah tabel, dengan : 

Judul : Notifikasi Potensi Lost Sales

Kolom : Barcode, Nama Barang, Stok Saat Ini, ADS (average daily sales) 
# 

Terimakasih.

**Comment by AbuMuhammad** [comment]
InsyaAllah sudah selesai pak.
Untuk menjalankan scriptnya bisa dieksekusi script di bawah ini atau tambahkan di cron

`.../ahadpos3/protected/yiic npls`

Contoh Tampilannya:
![screenshot-npls-frontpage](https://cloud.githubusercontent.com/assets/3438768/19062519/0e102ab6-8a25-11e6-8cca-cfa5f7a72cbd.png)

**Comment by sufehmi** [comment]
Alhamdulillah, baik pak, terimakasih banyak.

Mohon bantuan untuk setup ini di Ceger, dan lalu kita test & pantau bersama

Terimakasih.
