### ISSUE TITLE
AP2 : nominal berbeda dengan total nilai invoice

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#16]
Maaf numpang issue AP2 (ahadpos2) 

Nota nomor 31166 di Ahad Pondok Kacang, tercantum "Nominal" nya adalah 2.319.350

Padahal total invoice nya sebetulnya adalah 2.617.750

Saya cek juga nota aslinya, dan benar 2.617.750
# 

Terlampir file CSV dari Gudang untuk nota ini, yang kemudian di input di Ahad Pondok Kacang..

Mohon bantuan investigasi, apakah ini bug atau masalah lainnya.

Terimakasih.

[0103160802742-Ahad Pondok Kacang-2016-08-25--16-38.csv.txt](https://github.com/AbuMuhammad/ap3/files/488843/0103160802742-Ahad.Pondok.Kacang-2016-08-25--16-38.csv.txt)

![dsc_0298](https://cloud.githubusercontent.com/assets/170206/18773861/68cab1a2-817d-11e6-996d-c8c0b51a4559.JPG)

**Comment by sufehmi** [comment]
Kalau tidak salah ini sudah resolved ya? Mohon agar bisa di close, terimakasih

**Comment by AbuMuhammad** [comment]
Saya lupa, he.. 
Sudah tidak relevan karena Ahadmart Pondok Kacang sudah beralih ke ahadPOS3
