### ISSUE TITLE
Laporan Slow Moving per Supplier

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#17]
Mohon agar bisa ada laporan slow moving items per supplier.

Terimakasih.

**Comment by AbuMuhammad** [comment]
Apakah yang dimaksud sama dengan laporan aging / umur barang pak?

**Comment by sufehmi** [comment]
Aging berdasarkan umur,

Sedangkan slow moving itu:

= ( umur barang : periode waktu )

Yang paling kecil adalah slow moving

Sebetulnya seperti Top Rank, hanya dibalik saja

Terimakasih

**Comment by AbuMuhammad** [comment]
[Sudah selesai](https://github.com/AbuMuhammad/ap3/commit/252875f0f7c1eab6e9a7068b6b59df652ef8b388)
![screenshot_top_rank_tambahan_slow_moving](https://cloud.githubusercontent.com/assets/3438768/25510953/0493597a-2bee-11e7-9f1b-ce705ac0484d.png)

**Comment by AbuMuhammad** [comment]
Dijadikan satu dengan laporan Top Rank

**Comment by AbuMuhammad** [comment]
Per Supplier nya belum

**Comment by AbuMuhammad** [comment]
InsyaAllah sudah [selesai](https://github.com/AbuMuhammad/ap3/commit/a235a435ca7eefd7588fac5e68b388f1544a4b51)
![screenshot_top_rank_tambahan_slow_moving_profilid](https://cloud.githubusercontent.com/assets/3438768/25511742/fb5d9afa-2bf2-11e7-93f3-20ba99111fda.png)
