### ISSUE TITLE
FR (feature request) : Tag

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#19]
Sejak beberapa tahun yang lalu, sudah mulai terasa keterbatasan kategori, kurang fleksibel. Seperti tidak bisa ada lebih dari satu kategori untuk suatu item

Mohon agar bisa ada fitur "Tag", dimana bisa ada lebih dari satu tag untuk setiap item

Saya sedang buatkan desain databasenya, saya akan reply kesini

Terimakasih

**Comment by AbuMuhammad** [comment]
[Sudah selesai](https://github.com/AbuMuhammad/ap3/commit/38bf3786f18ecfecfcbc519067fcddfea4dc4ff8)
