### ISSUE TITLE
Laporan : Pembelian

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#2]
Saat ini belum ada laporan input pembelian.

Ini dibutuhkan saat manajemen melakukan kontrol toko harian. 
(untuk crosscheck antara nota supplier dengan data yang sudah di input)

Thanks.

**Comment by AbuMuhammad** [comment]
Jika yang dibutuhkan adalah seperti yang di ahadpos2, maka bisa lewat: Transaksi->Pembelian.
Di sana bisa difilter mau tanggal berapa, dan/atau suppliernya siapa, 
bisa juga dengan filter nomor nota dari supplier (jika diinput), serta bisa juga filter status: draft, hutang, lunas
