### ISSUE TITLE
Manual Aplikasi

### ISSUE THREAD

**Issue by pancaz** [AbuMuhammad/ap3#22]
Karena saya beberapa kali dibuat bingung dengan aplikasinya jadi saya mohon agar disertakan buku panduan atau manual aplikasi

**Comment by AbuMuhammad** [comment]
Bingung? Itu wajar, kalau menghadapi hal yang baru. Manual Aplikasi sepertinya belum akan dalam waktu dekat. Karena aplikasi masih butuh pengembangan
