### ISSUE TITLE
Tanya login

### ISSUE THREAD

**Issue by andriansahj** [AbuMuhammad/ap3#27]
Halo bagaimana login ke ahadpos ini?
saya login ke localhost/ap3/ lalu di redirect ke http://localhost/ap3/app/login dengan error 404

Terima kasih

**Comment by myzahron** [comment]
bisa dilihat struktur folder ap3-nya?

**Comment by AbuMuhammad** [comment]
Mungkin mod rewrite apache nya belum diaktifkan?

**Comment by sufehmi** [comment]
Isu ini sudah selesai? Di close saja?

**Comment by AbuMuhammad** [comment]
Iya. Sepertinya hanya masalah mod_rewrite nya belum diaktifkan
