### ISSUE TITLE
Error saat lihat detail barang karena set kode toko dengan huruf

### ISSUE THREAD

**Issue by aryasuryawan** [AbuMuhammad/ap3#28]
Assalamu'alaikum warohmatullohi wabarokatuh

Pak, izin mendokumentasikan bugs yang kami temui di toko kami di padang
**Masalahnya saat lihat data Barang di Config Barang** , lalu lihat detail barang dengan klik link barangnya [error terlampir]

> Error: CDbException
> 
> CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dc01011705000001' in 'where clause'. The SQL statement executed was: SELECT * FROM `pembelian` `t` WHERE nomor=dc01011705000001 LIMIT 1
> 
> /var/www/html/ap3/framework/db/CDbCommand.php(543)
> 

Setelah dicek, ternyata penyebabnya karena kode toko diset dengan huruf, dalam hal ini dc.

karena masih awam, jadi taunya cuma ubah manual saja di tabel terkait (pembelian dan inventory balance) dengan query sederhana

> UPDATE `inventory_balance` SET `nomor_dokumen` = replace(nomor_dokumen, 'no_dokumenlama', 'no_dokumenbaru')
> 
> UPDATE `pembelian` SET `nomor` = replace(nomor, 'no_dokumenlama', 'no_dokumenbaru')

![screenshot from 2017-07-15 06-52-42](https://user-images.githubusercontent.com/28218735/28234481-3d45cb08-692a-11e7-9b8a-52629265795a.png)

**Comment by AbuMuhammad** [comment]
Kode toko harus angka

**Comment by AbuMuhammad** [comment]
Dan.. itu bukan bug. Kode toko harus dua digit (desimal)

**Comment by aryasuryawan** [comment]
Sip, syukron pak

Pada tanggal 15 Jul 2017 1.16 PM, "Abu Muhammad" <notifications@github.com>
menulis:

Closed #28 <https://github.com/AbuMuhammad/ap3/issues/28>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AbuMuhammad/ap3/issues/28#event-1165203420>, or mute
the thread
