### ISSUE TITLE
Tolong Sertakan database

### ISSUE THREAD

**Issue by imcahyo** [AbuMuhammad/ap3#29]
Ahad pos 3 tidak bisa di Instal error database tidak ditemukan, sudah buat baru tablenya juga error, tidak bisa buat database secara otomatis, bisa tolong sertakan database secara terpisah?

**Comment by AbuMuhammad** [comment]
Sudah ada, harap baca INSTALL.TXT

**Comment by imcahyo** [comment]
aku instal diwindows dengan xampp 3.0.12 sudah aku coba tapi gagal terus, database tidak bisa dibuat otomatis,

Fresh Install Process..

Droping Database ahadpos3..

Database Dropped!
Creating Database ahadpos3..

Database Created!
Migrating Database..

Cuma muncul tulisan seperti itu

**Comment by AbuMuhammad** [comment]
Ya.. memang proses fresh-install didesain untuk jalan di linux. Database
saya tidak menyiapkan dalam bentuk script .sql karena setiap update berarti
saya harus menyiapkan lagi script .sql nya.. ribet.
Kalau di windows coba edit file fresh-install.php nya. Cari yang ada
tulisan "yiic" ganti dengan "yiic.bat".
Mudah2an bisa ya, saya belum pernah coba di windows soalnya

**Comment by AbuMuhammad** [comment]
Jangan lupa, sesuaikan juga file protected/config/db.php

**Comment by imcahyo** [comment]
Aku akhirnya coba manual, tapi masih banyak yang error, kalau boleh aku minta export databasenya dong
kirim ke email imax03 at gmail.com

![ap3](https://user-images.githubusercontent.com/30273973/28507135-a4fac8b6-705a-11e7-8f7c-6a44ad8d58bf.jpg)

**Comment by myzahron** [comment]
Setelah create database, jalankan script:
c:\xampp\php>php c:\xampp\htdocs\ap3\protected\yiic migrate

(hanya untuk xampp, windows)

**Comment by aryasuryawan** [comment]
Kalau di saya berhasil pakai  yang ini. Setelah create database, jalankan script:
c:\xampp\php\php.exe c:\xampp\htdocs\ap3\protected\yiic migrate

(hanya untuk xampp, windows)
