### ISSUE TITLE
Autocomplete=off :: untuk Input Type=password

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#3]
Mohon agar input type password bisa dimatikan semua fotur auto complete nya.
Karena user sering luput mematikan fitur autocomplete di browser mereka.

Detail terlampir.

Terimakasih.

![screenshot from 2016-05-17 13-10-35](https://cloud.githubusercontent.com/assets/170206/15312785/11f1c70a-1c31-11e6-822a-af1e06b9b97b.png)

**Comment by AbuMuhammad** [comment]
done
[cek commit](https://github.com/AbuMuhammad/ap3/commit/f55ec6665bc97bbef0ec731cd7c828d9f29324aa)
