### ISSUE TITLE
Printer kadang tidak bisa cetak struk

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#30]
Laporan dari tim Dayamart via Whatsapp sbb :

"Assalamualaikum pak, maaf mengganggu. Sebelum terima kasih. Mau minta bantuan, utk ap3 di linux, setting printer sdh sesuai di ap3. Printing kadang bisa, kadang tidak. Itu problemnya di mana y pak"

Kita akan manfaatkan thread ini untuk troubleshooting, terimakasih

**Comment by AbuMuhammad** [comment]
Mungkin di networknya? Atau sistemnya? Masalah begini biasanya teknisi
(hardware/network) lebih tahu.
Kalau untuk ap3 nya sudah diuji di ahadmart. Kode nya sama

On 14 Oct 2017 15:16, "Harry Sufehmi" <notifications@github.com> wrote:
>
> Laporan dari tim Dayamart via Whatsapp sbb :
>
> "Assalamualaikum pak, maaf mengganggu. Sebelum terima kasih. Mau minta
bantuan, utk ap3 di linux, setting printer sdh sesuai di ap3. Printing
kadang bisa, kadang tidak. Itu problemnya di mana y pak"

**Comment by sufehmi** [comment]
Barusan saya kontak telpon tim Dayamart, ternyata ini lokasi baru di Pasar Minggu 🙏

Nampaknya pak Rozi perlu site visit, troubleshooting langsung di lokasi. Saya akan coba kontak beliau.

**Comment by AbuMuhammad** [comment]
Solusi: Install Printer dengan driver generic/text karena akan digunakan secara raw printing. Portnya pilih usb, walaupun tulisannya unknown.
Update cups (opsional). 
Print struk menggunakan pop up, jadi diaable protectionnya atau tambah exception untuk alamat server di mana ahadpos3 berada

**Comment by sufehmi** [comment]
Terima kasih

**Comment by aryasuryawan** [comment]
Terima kasih pak Bambang.

Kemarin, kalau g salah ditambah konfigurasi di CUPS basic configuration

Centang : (v) Allow printing from internet
