### ISSUE TITLE
FR : laporan pergerakan barang @ AhadDC

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#32]
Per diskusi via telpon :

- pilih toko
- pilih range tanggal / periode laporan
- pilih laporan retur atau transfer barang
- submit

Lalu tampil semua barang terkait, kolom : 

Barcode
Nama barang
Jumlah
Harga modal

berikut total nilai stok seluruhnya

Terimakasih

**Comment by AbuMuhammad** [comment]
Selesai
