### ISSUE TITLE
Tanya: assignment item utk hak akses cetak label rak

### ISSUE THREAD

**Issue by aryasuryawan** [AbuMuhammad/ap3#33]
Bismillah, pak izin Tanya: assignment item utk hak akses cetak label rak.

Kemarin kan sdh update ap3 via git. Ada beberapa menu yg beda, termasuk soal assign hak akses. Saya belum menemukan pilihan untuk memberikan akses cetak label rak utk user non admin.

Mohon bantuannya
.syukron

**Comment by AbuMuhammad** [comment]
assignment digabung di "user". Config -> Akses -> User. Lihat di kolom paling kanan

**Comment by aryasuryawan** [comment]
Item otorisasi utk cetak label rak maksudnya

**Comment by AbuMuhammad** [comment]
Kalau belum ada, silahkan ditambah sendiri :senyum, karena itu setting-an. Ikuti yang yang sudah ada, seperti cetak form so. Bisa ditambah di Config -> Akses -> Item Otorisasi.
Nama item otorisasi adalah nama aksi / url / link yang bisa diakses. Jadi jika di sebuah form ada tombol, maka jika linknya beda, maka itu juga dimasukkan ke item otorisasi.

Kemudian baru di assign

PS: Insya Allah suatu saat nanti akan ditambahkan auto generate item otorisasi yang ada di sistem. Sementara ini, manual, menyesuaikan keperluan masing-masing toko

**Comment by AbuMuhammad** [comment]
Sudah ada fitur [auto generate item otorisasi](https://github.com/AbuMuhammad/ap3/commit/aa67abdc0eede88ca866d591a67d6739c5221e9c)
Config - Akses - Item Otorisasi: Tambah
![screenshot ahadpos - tambah item](https://user-images.githubusercontent.com/3438768/32151895-00a77732-bd53-11e7-8dcb-3c29566ee6ae.jpg)
Walaupun item bisa langsung di _assign_ ke _User_.
_Ahsan_:
_Item_ dikelompokkan ke dalam _Task_
_Task_ dikelompokkan ke dalam _Role_
_Role_ yang di _assign_ ke _User_

**Comment by aryasuryawan** [comment]
Terima kasih

Pada tanggal 30 Okt 2017 9.20 AM, "Abu Muhammad" <notifications@github.com>
menulis:
