### ISSUE TITLE
FR: Print Laporan Pengeluaran/penerimaan

### ISSUE THREAD

**Issue by aryasuryawan** [AbuMuhammad/ap3#34]
Bismillah, pak apakah memungkinkan ada fitur print dan export csv Laporan Pengeluaran/penerimaan?

Soalnya blm ada

**Comment by AbuMuhammad** [comment]
Ya.., mungkin saja

**Comment by AbuMuhammad** [comment]
Sudah ada pak
[commit 824fa27e87f092c582d59ea8ddbc4841e754b1bd](https://github.com/AbuMuhammad/ap3/commit/824fa27e87f092c582d59ea8ddbc4841e754b1bd)

**Comment by aryasuryawan** [comment]
alhamdulillah
