### ISSUE TITLE
Error setelah update PHP

### ISSUE THREAD

**Issue by myzahron** [AbuMuhammad/ap3#36]
Setelah upgrade ke PHP versi 7.2.0, terjadi error pada saat membuka aplikasi.

Setelah diupdate pada file:  https://github.com/AbuMuhammad/ap3/blob/develop/protected/components/PublicController.php baris 19 
dari : 
`public $boxHeader = '';`

Menjadi:
`public $boxHeader = ['normal' => '', 'small' => ''];`

kemudian aplikasi dapat berjalan normal kembali.

**Comment by AbuMuhammad** [comment]
Sudah diupdate
[5ac7c69347cc7d7ee1a60f8a3b676414b667404e](https://github.com/AbuMuhammad/ap3/commit/5ac7c69347cc7d7ee1a60f8a3b676414b667404e)
Terimakasih
