### ISSUE TITLE
Laporan Pembelian : hanya bisa filter berdasarkan tanggal

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#4]
Tidak bisa jika tanggal-bulan

Contoh: mengetikkan"18" di tanggal akan menghasilkan screenshot terlampir.

Namun, mengetikkan "18-05" tidak akan menampilkan apa pun.

Terimakasih.

![screenshot from 2016-05-18 20-16-16](https://cloud.githubusercontent.com/assets/170206/15359845/65c4ff82-1d35-11e6-85f3-7cba8cce0196.png)

**Comment by AbuMuhammad** [comment]
Saat ini filter nya baru bisa dg format yyyy-mm-dd.
Jadi kalau tgl 18 mei, maka diinput 05-18

**Comment by sufehmi** [comment]
Sekarang sudah bisa dd-mm-yyyy, terimakasih.
