### ISSUE TITLE
Input Pembelian :: harga jual jadi pecahan

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#5]
Saat input pembelian, harga jual bisa dibantu dihitung otomatis oleh komputer - dan kadang menjadi pecahan.

Mohon agar bisa otomatis dibulatkan ke atas, satuan 50.

Contoh : 

14.331 = dibulatkan menjadi 14.350
2.627 = dibulatkan menjadi 2.650
8.573 = dibulatkan menjadi 8.600

===

Selanjutnya : satuan pembulatan bisa diatur dari menu Config, 
default 50, bisa diubah.

Terimakasih.

**Comment by AbuMuhammad** [comment]
Selesai
[50c890f3bff1e55f6d3ec9af964aae743c7101b1](https://github.com/AbuMuhammad/ap3/commit/50c890f3bff1e55f6d3ec9af964aae743c7101b1)
