### ISSUE TITLE
Instalasi error di MySQL versi 5.7

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#6]
Saat instalasi menjalankan fresh-install.sh di MySQL 5.7 (bawaan Ubuntu 16.04), muncul error terlampir.

Solusi: ganti semua string "0000-00-00" menjadi "2000-01-01"

Terimakasih.

================
> create table template 1 ...Exception: CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'. 

The SQL statement executed was: CREATE TABLE `template 1` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`nama` varchar(45) NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`updated_by` int(11) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `nama` (`nama`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 

(/var/www/html/ap3/framework/db/CDbCommand.php:358)

**Comment by AbuMuhammad** [comment]
[Selesai](https://github.com/AbuMuhammad/ap3/commit/63cd6e660a77f5b8818e863b3513b77362ed15f6)
