### ISSUE TITLE
Error saat eksekusi fresh-install.sh / inisialisasi database

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#7]
Ketika fresh-install.sh dijalankan di MySQL 5.7 (bawaan Ubuntu 16.04), muncul pesan error sbb.

Terimakasih.

===========

    > insert into config ...Exception: CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'nilai' cannot be null. The SQL statement executed was: INSERT INTO `config` (`nama`, `nilai`, `deskripsi`, `updated_at`, `updated_by`, `created_at`) VALUES (:nama_0, :nilai_0, :deskripsi_0, :updated_at_0, :updated_by_0, :created_at_0), (:nama_1, :nilai_1, :deskripsi_1, :updated_at_1, :updated_by_1, :created_at_1), (:nama_2, :nilai_2, :deskripsi_2, :updated_at_2, :updated_by_2, :created_at_2), (:nama_3, :nilai_3, :deskripsi_3, :updated_at_3, :updated_by_3, :created_at_3), (:nama_4, :nilai_4, :deskripsi_4, :updated_at_4, :updated_by_4, :created_at_4), (:nama_5, :nilai_5, :deskripsi_5, :updated_at_5, :updated_by_5, :created_at_5), (:nama_6, :nilai_6, :deskripsi_6, :updated_at_6, :updated_by_6, :created_at_6), (:nama_7, :nilai_7, :deskripsi_7, :updated_at_7, :updated_by_7, :created_at_7), (:nama_8, :nilai_8, :deskripsi_8, :updated_at_8, :updated_by_8, :created_at_8), (:nama_9, NULL, :deskripsi_9, :updated_at_9, :updated_by_9, :created_at_9), (:nama_10, NULL, :deskripsi_10, :updated_at_10, :updated_by_10, :created_at_10), (:nama_11, NULL, :deskripsi_11, :updated_at_11, :updated_by_11, :created_at_11), (:nama_12, NULL, :deskripsi_12, :updated_at_12, :updated_by_12, :created_at_12), (:nama_13, :nilai_13, :deskripsi_13, :updated_at_13, :updated_by_13, :created_at_13). Bound with :nama_0='toko.nama', :nilai_0='Toko Mart', :deskripsi_0='Nama Toko', :updated_at_0='2001-01-01 00:00:00', :updated_by_0='1', :created_at_0='2001-01-01 00:00:00', :nama_1='toko.kode', :nilai_1='01', :deskripsi_1='Kode Toko', :updated_at_1='2001-01-01 00:00:00', :updated_by_1='1', :created_at_1='2001-01-01 00:00:00', :nama_2='toko.alamat1', :nilai_2='0', :deskripsi_2='Alamat 1', :updated_at_2='2001-01-01 00:00:00', :updated_by_2='1', :created_at_2='2001-01-01 00:00:00', :nama_3='toko.alamat2', :nilai_3='0', :deskripsi_3='Alamat 2', :updated_at_3='2001-01-01 00:00:00', :updated_by_3='1', :created_at_3='2001-01-01 00:00:00', :nama_4='toko.alamat3', :nilai_4='0', :deskripsi_4='Alamat 3', :updated_at_4='2001-01-01 00:00:00', :updated_by_4='1', :created_at_4='2001-01-01 00:00:00', :nama_5='toko.telp', :nilai_5='0', :deskripsi_5='Telp', :updated_at_5='2001-01-01 00:00:00', :updated_by_5='1', :created_at_5='2001-01-01 00:00:00', :nama_6='toko.email', :nilai_6='toko@mart.com', :deskripsi_6='E-mail', :updated_at_6='2001-01-01 00:00:00', :updated_by_6='1', :created_at_6='2001-01-01 00:00:00', :nama_7='penjualan.jatuh_tempo', :nilai_7='7', :deskripsi_7='Jatuh tempo pembayaran untuk penjualan (hari)', :updated_at_7='2001-01-01 00:00:00', :updated_by_7='1', :created_at_7='2001-01-01 00:00:00', :nama_8='keuangan.saldo_awal', :nilai_8='0', :deskripsi_8='Saldo Awal', :updated_at_8='2001-01-01 00:00:00', :updated_by_8='1', :created_at_8='2001-01-01 00:00:00', :nama_9='struk.header1', :deskripsi_9='Header 1 struk penjualan', :updated_at_9='2001-01-01 00:00:00', :updated_by_9='1', :created_at_9='2001-01-01 00:00:00', :nama_10='struk.header2', :deskripsi_10='Header 2 struk penjualan', :updated_at_10='2001-01-01 00:00:00', :updated_by_10='1', :created_at_10='2001-01-01 00:00:00', :nama_11='struk.footer1', :deskripsi_11='Footer 1 struk penjualan', :updated_at_11='2001-01-01 00:00:00', :updated_by_11='1', :created_at_11='2001-01-01 00:00:00', :nama_12='struk.footer2', :deskripsi_12='Footer 2 struk penjualan', :updated_at_12='2001-01-01 00:00:00', :updated_by_12='1', :created_at_12='2001-01-01 00:00:00', :nama_13='pos.autoprint', :nilai_13='1', :deskripsi_13='Langsung print ketika disimpan', :updated_at_13='2001-01-01 00:00:00', :updated_by_13='1', :created_at_13='2001-01-01 00:00:00' (/var/www/html/ap3/framework/db/CDbCommand.php:358)

**Comment by sufehmi** [comment]
Ups output fresh-install.sh ternyata di format, saya copas lagi disini tanpa formatting : 


===========


    > insert into config ...Exception: CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'nilai' cannot be null. The SQL statement executed was: INSERT INTO `config` (`nama`, `nilai`, `deskripsi`, `updated_at`, `updated_by`, `created_at`) VALUES (:nama_0, :nilai_0, :deskripsi_0, :updated_at_0, :updated_by_0, :created_at_0), (:nama_1, :nilai_1, :deskripsi_1, :updated_at_1, :updated_by_1, :created_at_1), (:nama_2, :nilai_2, :deskripsi_2, :updated_at_2, :updated_by_2, :created_at_2), (:nama_3, :nilai_3, :deskripsi_3, :updated_at_3, :updated_by_3, :created_at_3), (:nama_4, :nilai_4, :deskripsi_4, :updated_at_4, :updated_by_4, :created_at_4), (:nama_5, :nilai_5, :deskripsi_5, :updated_at_5, :updated_by_5, :created_at_5), (:nama_6, :nilai_6, :deskripsi_6, :updated_at_6, :updated_by_6, :created_at_6), (:nama_7, :nilai_7, :deskripsi_7, :updated_at_7, :updated_by_7, :created_at_7), (:nama_8, :nilai_8, :deskripsi_8, :updated_at_8, :updated_by_8, :created_at_8), (:nama_9, NULL, :deskripsi_9, :updated_at_9, :updated_by_9, :created_at_9), (:nama_10, NULL, :deskripsi_10, :updated_at_10, :updated_by_10, :created_at_10), (:nama_11, NULL, :deskripsi_11, :updated_at_11, :updated_by_11, :created_at_11), (:nama_12, NULL, :deskripsi_12, :updated_at_12, :updated_by_12, :created_at_12), (:nama_13, :nilai_13, :deskripsi_13, :updated_at_13, :updated_by_13, :created_at_13). Bound with :nama_0='toko.nama', :nilai_0='Toko Mart', :deskripsi_0='Nama Toko', :updated_at_0='2001-01-01 00:00:00', :updated_by_0='1', :created_at_0='2001-01-01 00:00:00', :nama_1='toko.kode', :nilai_1='01', :deskripsi_1='Kode Toko', :updated_at_1='2001-01-01 00:00:00', :updated_by_1='1', :created_at_1='2001-01-01 00:00:00', :nama_2='toko.alamat1', :nilai_2='0', :deskripsi_2='Alamat 1', :updated_at_2='2001-01-01 00:00:00', :updated_by_2='1', :created_at_2='2001-01-01 00:00:00', :nama_3='toko.alamat2', :nilai_3='0', :deskripsi_3='Alamat 2', :updated_at_3='2001-01-01 00:00:00', :updated_by_3='1', :created_at_3='2001-01-01 00:00:00', :nama_4='toko.alamat3', :nilai_4='0', :deskripsi_4='Alamat 3', :updated_at_4='2001-01-01 00:00:00', :updated_by_4='1', :created_at_4='2001-01-01 00:00:00', :nama_5='toko.telp', :nilai_5='0', :deskripsi_5='Telp', :updated_at_5='2001-01-01 00:00:00', :updated_by_5='1', :created_at_5='2001-01-01 00:00:00', :nama_6='toko.email', :nilai_6='toko@mart.com', :deskripsi_6='E-mail', :updated_at_6='2001-01-01 00:00:00', :updated_by_6='1', :created_at_6='2001-01-01 00:00:00', :nama_7='penjualan.jatuh_tempo', :nilai_7='7', :deskripsi_7='Jatuh tempo pembayaran untuk penjualan (hari)', :updated_at_7='2001-01-01 00:00:00', :updated_by_7='1', :created_at_7='2001-01-01 00:00:00', :nama_8='keuangan.saldo_awal', :nilai_8='0', :deskripsi_8='Saldo Awal', :updated_at_8='2001-01-01 00:00:00', :updated_by_8='1', :created_at_8='2001-01-01 00:00:00', :nama_9='struk.header1', :deskripsi_9='Header 1 struk penjualan', :updated_at_9='2001-01-01 00:00:00', :updated_by_9='1', :created_at_9='2001-01-01 00:00:00', :nama_10='struk.header2', :deskripsi_10='Header 2 struk penjualan', :updated_at_10='2001-01-01 00:00:00', :updated_by_10='1', :created_at_10='2001-01-01 00:00:00', :nama_11='struk.footer1', :deskripsi_11='Footer 1 struk penjualan', :updated_at_11='2001-01-01 00:00:00', :updated_by_11='1', :created_at_11='2001-01-01 00:00:00', :nama_12='struk.footer2', :deskripsi_12='Footer 2 struk penjualan', :updated_at_12='2001-01-01 00:00:00', :updated_by_12='1', :created_at_12='2001-01-01 00:00:00', :nama_13='pos.autoprint', :nilai_13='1', :deskripsi_13='Langsung print ketika disimpan', :updated_at_13='2001-01-01 00:00:00', :updated_by_13='1', :created_at_13='2001-01-01 00:00:00' (/var/www/html/ap3/framework/db/CDbCommand.php:358)



===========


   insert into config ...Exception: CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'nilai' cannot be null. The SQL statement executed was: INSERT INTO `config` (`nama`, `nilai`, `deskripsi`, `updated_at`, `updated_by`, `created_at`) VALUES (:nama_0, :nilai_0, :deskripsi_0, :updated_at_0, :updated_by_0, :created_at_0), (:nama_1, :nilai_1, :deskripsi_1, :updated_at_1, :updated_by_1, :created_at_1), (:nama_2, :nilai_2, :deskripsi_2, :updated_at_2, :updated_by_2, :created_at_2), (:nama_3, :nilai_3, :deskripsi_3, :updated_at_3, :updated_by_3, :created_at_3), (:nama_4, :nilai_4, :deskripsi_4, :updated_at_4, :updated_by_4, :created_at_4), (:nama_5, :nilai_5, :deskripsi_5, :updated_at_5, :updated_by_5, :created_at_5), (:nama_6, :nilai_6, :deskripsi_6, :updated_at_6, :updated_by_6, :created_at_6), (:nama_7, :nilai_7, :deskripsi_7, :updated_at_7, :updated_by_7, :created_at_7), (:nama_8, :nilai_8, :deskripsi_8, :updated_at_8, :updated_by_8, :created_at_8), (:nama_9, NULL, :deskripsi_9, :updated_at_9, :updated_by_9, :created_at_9), (:nama_10, NULL, :deskripsi_10, :updated_at_10, :updated_by_10, :created_at_10), (:nama_11, NULL, :deskripsi_11, :updated_at_11, :updated_by_11, :created_at_11), (:nama_12, NULL, :deskripsi_12, :updated_at_12, :updated_by_12, :created_at_12), (:nama_13, :nilai_13, :deskripsi_13, :updated_at_13, :updated_by_13, :created_at_13). Bound with :nama_0='toko.nama', :nilai_0='Toko Mart', :deskripsi_0='Nama Toko', :updated_at_0='2001-01-01 00:00:00', :updated_by_0='1', :created_at_0='2001-01-01 00:00:00', :nama_1='toko.kode', :nilai_1='01', :deskripsi_1='Kode Toko', :updated_at_1='2001-01-01 00:00:00', :updated_by_1='1', :created_at_1='2001-01-01 00:00:00', :nama_2='toko.alamat1', :nilai_2='0', :deskripsi_2='Alamat 1', :updated_at_2='2001-01-01 00:00:00', :updated_by_2='1', :created_at_2='2001-01-01 00:00:00', :nama_3='toko.alamat2', :nilai_3='0', :deskripsi_3='Alamat 2', :updated_at_3='2001-01-01 00:00:00', :updated_by_3='1', :created_at_3='2001-01-01 00:00:00', :nama_4='toko.alamat3', :nilai_4='0', :deskripsi_4='Alamat 3', :updated_at_4='2001-01-01 00:00:00', :updated_by_4='1', :created_at_4='2001-01-01 00:00:00', :nama_5='toko.telp', :nilai_5='0', :deskripsi_5='Telp', :updated_at_5='2001-01-01 00:00:00', :updated_by_5='1', :created_at_5='2001-01-01 00:00:00', :nama_6='toko.email', :nilai_6='toko@mart.com', :deskripsi_6='E-mail', :updated_at_6='2001-01-01 00:00:00', :updated_by_6='1', :created_at_6='2001-01-01 00:00:00', :nama_7='penjualan.jatuh_tempo', :nilai_7='7', :deskripsi_7='Jatuh tempo pembayaran untuk penjualan (hari)', :updated_at_7='2001-01-01 00:00:00', :updated_by_7='1', :created_at_7='2001-01-01 00:00:00', :nama_8='keuangan.saldo_awal', :nilai_8='0', :deskripsi_8='Saldo Awal', :updated_at_8='2001-01-01 00:00:00', :updated_by_8='1', :created_at_8='2001-01-01 00:00:00', :nama_9='struk.header1', :deskripsi_9='Header 1 struk penjualan', :updated_at_9='2001-01-01 00:00:00', :updated_by_9='1', :created_at_9='2001-01-01 00:00:00', :nama_10='struk.header2', :deskripsi_10='Header 2 struk penjualan', :updated_at_10='2001-01-01 00:00:00', :updated_by_10='1', :created_at_10='2001-01-01 00:00:00', :nama_11='struk.footer1', :deskripsi_11='Footer 1 struk penjualan', :updated_at_11='2001-01-01 00:00:00', :updated_by_11='1', :created_at_11='2001-01-01 00:00:00', :nama_12='struk.footer2', :deskripsi_12='Footer 2 struk penjualan', :updated_at_12='2001-01-01 00:00:00', :updated_by_12='1', :created_at_12='2001-01-01 00:00:00', :nama_13='pos.autoprint', :nilai_13='1', :deskripsi_13='Langsung print ketika disimpan', :updated_at_13='2001-01-01 00:00:00', :updated_by_13='1', :created_at_13='2001-01-01 00:00:00' (/var/www/html/ap3/framework/db/CDbCommand.php:358)

**Comment by sufehmi** [comment]
Solusi :

Cari string ini : 

=====
            array('nama' => 'struk.header1', 'deskripsi' => 'Header 1 struk penjualan', 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'struk.header2', 'deskripsi' => 'Header 2 struk penjualan', 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'struk.footer1', 'deskripsi' => 'Footer 1 struk penjualan', 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'struk.footer2', 'deskripsi' => 'Footer 2 struk penjualan', 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
=======

Dan lalu ganti menjadi ini : 

=======
            array('nama' => 'struk.header1', 'nilai' => '', 'deskripsi' => 'Header 1 struk penjualan', 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'struk.header2', 'nilai' => '', 'deskripsi' => 'Header 2 struk penjualan', 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'struk.footer1', 'nilai' => '', 'deskripsi' => 'Footer 1 struk penjualan', 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'struk.footer2', 'nilai' => '', 'deskripsi' => 'Footer 2 struk penjualan', 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
======

Terimakasih.

**Comment by sufehmi** [comment]
atau hilangkan string "NOT NULL" dari definisi column "nilai"

**Comment by AbuMuhammad** [comment]
[Selesai](https://github.com/AbuMuhammad/ap3/commit/63cd6e660a77f5b8818e863b3513b77362ed15f6)
