### ISSUE TITLE
Error SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'jenis' cannot be null

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#8]
Muncul error sbb saat menjalankan fresh-install.sh :

===============
    insert into item_keuangan ...Exception: CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'jenis' cannot be null. The SQL statement executed was: INSERT INTO `item_keuangan` (`id`, `nama`, `updated_at`, `updated_by`, `created_at`, `parent_id`, `jenis`) VALUES (:id_0, :nama_0, :updated_at_0, :updated_by_0, :created_at_0, NULL, NULL), (:id_1, :nama_1, :updated_at_1, :updated_by_1, :created_at_1, :parent_id_1, NULL), (:id_2, :nama_2, :updated_at_2, :updated_by_2, :created_at_2, NULL, :jenis_2), (:id_3, :nama_3, :updated_at_3, :updated_by_3, :created_at_3, :parent_id_3, :jenis_3), (:id_4, :nama_4, :updated_at_4, :updated_by_4, :created_at_4, :parent_id_4, :jenis_4), (:id_5, :nama_5, :updated_at_5, :updated_by_5, :created_at_5, :parent_id_5, NULL), (:id_6, :nama_6, :updated_at_6, :updated_by_6, :created_at_6, NULL, NULL), (:id_7, :nama_7, :updated_at_7, :updated_by_7, :created_at_7, NULL, NULL), (:id_8, :nama_8, :updated_at_8, :updated_by_8, :created_at_8, NULL, :jenis_8), (NULL, :nama_9, :updated_at_9, :updated_by_9, :created_at_9, :parent_id_9, NULL), (NULL, :nama_10, :updated_at_10, :updated_by_10, :created_at_10, :parent_id_10, NULL), (NULL, :nama_11, :updated_at_11, :updated_by_11, :created_at_11, :parent_id_11, NULL), (NULL, :nama_12, :updated_at_12, :updated_by_12, :created_at_12, :parent_id_12, NULL), (NULL, :nama_13, :updated_at_13, :updated_by_13, :created_at_13, :parent_id_13, NULL), (NULL, :nama_14, :updated_at_14, :updated_by_14, :created_at_14, :parent_id_14, NULL), (NULL, :nama_15, :updated_at_15, :updated_by_15, :created_at_15, :parent_id_15, NULL), (NULL, :nama_16, :updated_at_16, :updated_by_16, :created_at_16, :parent_id_16, NULL), (NULL, :nama_17, :updated_at_17, :updated_by_17, :created_at_17, :parent_id_17, :jenis_17). Bound with :id_0='1', :nama_0='Bayar Hutang', :updated_at_0='2000-01-01 00:00:00', :updated_by_0='1', :created_at_0='2000-01-01 00:00:00', :id_1='2', :nama_1='Pembelian', :updated_at_1='2000-01-01 00:00:00', :updated_by_1='1', :created_at_1='2000-01-01 00:00:00', :parent_id_1='1', :id_2='3', :nama_2='Penerimaan Piutang', :updated_at_2='2000-01-01 00:00:00', :updated_by_2='1', :created_at_2='2000-01-01 00:00:00', :jenis_2=1, :id_3='4', :nama_3='Penjualan', :updated_at_3='2000-01-01 00:00:00', :updated_by_3='1', :created_at_3='2000-01-01 00:00:00', :parent_id_3='3', :jenis_3=1, :id_4='5', :nama_4='Retur Beli', :updated_at_4='2000-01-01 00:00:00', :updated_by_4='1', :created_at_4='2000-01-01 00:00:00', :parent_id_4='3', :jenis_4=1, :id_5='6', :nama_5='Retur Jual', :updated_at_5='2000-01-01 00:00:00', :updated_by_5='1', :created_at_5='2000-01-01 00:00:00', :parent_id_5='1', :id_6='7', :nama_6='Expense', :updated_at_6='2000-01-01 00:00:00', :updated_by_6='1', :created_at_6='2000-01-01 00:00:00', :id_7='8', :nama_7='Non Expense', :updated_at_7='2000-01-01 00:00:00', :updated_by_7='1', :created_at_7='2000-01-01 00:00:00', :id_8='9', :nama_8='Pendapatan Lain', :updated_at_8='2000-01-01 00:00:00', :updated_by_8='1', :created_at_8='2000-01-01 00:00:00', :jenis_8=1, :nama_9='Listrik', :updated_at_9='2000-01-01 00:00:00', :updated_by_9='1', :created_at_9='2000-01-01 00:00:00', :parent_id_9='7', :nama_10='Alat Tulis Kantor', :updated_at_10='2000-01-01 00:00:00', :updated_by_10='1', :created_at_10='2000-01-01 00:00:00', :parent_id_10='7', :nama_11='Gaji Karyawan', :updated_at_11='2000-01-01 00:00:00', :updated_by_11='1', :created_at_11='2000-01-01 00:00:00', :parent_id_11='7', :nama_12='Internet', :updated_at_12='2000-01-01 00:00:00', :updated_by_12='1', :created_at_12='2000-01-01 00:00:00', :parent_id_12='7', :nama_13='Air Minum', :updated_at_13='2000-01-01 00:00:00', :updated_by_13='1', :created_at_13='2000-01-01 00:00:00', :parent_id_13='7', :nama_14='Sampah', :updated_at_14='2000-01-01 00:00:00', :updated_by_14='1', :created_at_14='2000-01-01 00:00:00', :parent_id_14='7', :nama_15='RT', :updated_at_15='2000-01-01 00:00:00', :updated_by_15='1', :created_at_15='2000-01-01 00:00:00', :parent_id_15='7', :nama_16='Kasbon', :updated_at_16='2000-01-01 00:00:00', :updated_by_16='1', :created_at_16='2000-01-01 00:00:00', :parent_id_16='8', :nama_17='Jual Kardus', :updated_at_17='2000-01-01 00:00:00', :updated_by_17='1', :created_at_17='2000-01-01 00:00:00', :parent_id_17='9', :jenis_17=1 (/var/www/html/ap3/framework/db/CDbCommand.php:358)
===============

SOLUSI :

Cari string sbb :      

===============
    $this->insertMultiple('item_keuangan', array(
            array('id' => 1, 'nama' => 'Bayar Hutang', 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 2, 'nama' => 'Pembelian', 'parent_id' => 1, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 3, 'nama' => 'Penerimaan Piutang', 'jenis' => 1, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 4, 'nama' => 'Penjualan', 'jenis' => 1, 'parent_id' => 3, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 5, 'nama' => 'Retur Beli', 'jenis' => 1, 'parent_id' => 3, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 6, 'nama' => 'Retur Jual', 'parent_id' => 1, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 7, 'nama' => 'Expense', 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 8, 'nama' => 'Non Expense', 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 9, 'nama' => 'Pendapatan Lain', 'jenis' => 1, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Listrik', 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Alat Tulis Kantor', 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Gaji Karyawan', 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Internet', 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Air Minum', 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Sampah', 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'RT', 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Kasbon', 'parent_id' => 8, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Jual Kardus', 'jenis' => 1, 'parent_id' => 9, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
===============

Lalu ganti menjadi sbb :

===============
        $this->insertMultiple('item_keuangan', array(
            array('id' => 1, 'nama' => 'Bayar Hutang', 'jenis' => 0, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 2, 'nama' => 'Pembelian', 'jenis' => 0, 'parent_id' => 1, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 3, 'nama' => 'Penerimaan Piutang', 'jenis' => 1, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 4, 'nama' => 'Penjualan', 'jenis' => 1, 'parent_id' => 3, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 5, 'nama' => 'Retur Beli', 'jenis' => 1, 'parent_id' => 3, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 6, 'nama' => 'Retur Jual', 'jenis' => 0, 'parent_id' => 1, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 7, 'nama' => 'Expense', 'jenis' => 0, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 8, 'nama' => 'Non Expense', 'jenis' => 0, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('id' => 9, 'nama' => 'Pendapatan Lain', 'jenis' => 1, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Listrik', 'jenis' => 0, 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Alat Tulis Kantor', 'jenis' => 0, 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Gaji Karyawan', 'jenis' => 0, 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Internet', 'jenis' => 0, 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Air Minum', 'jenis' => 0, 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Sampah', 'jenis' => 0, 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'RT', 'jenis' => 0, 'parent_id' => 7, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Kasbon', 'jenis' => 0, 'parent_id' => 8, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
            array('nama' => 'Jual Kardus', 'jenis' => 0, 'jenis' => 1, 'parent_id' => 9, 'updated_at' => '2000-01-01 00:00:00', 'updated_by' => 1, 'created_at' => '2000-01-01 00:00:00'),
===============

Terimakasih.

**Comment by AbuMuhammad** [comment]
[Selesai](https://github.com/AbuMuhammad/ap3/commit/63cd6e660a77f5b8818e863b3513b77362ed15f6)
