### ISSUE TITLE
Invalid datetime format: 1292 Incorrect datetime value: 'now()' for column 'updated_at'

### ISSUE THREAD

**Issue by sufehmi** [AbuMuhammad/ap3#9]
Saat menjalankan fresh-install.sh, muncul pesan error sbb :

     insert into config ...CDbException: CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 'now()' for column 'updated_at' at row 1. The SQL statement executed was: INSERT INTO `config` (`nama`, `nilai`, `deskripsi`, `updated_at`, `updated_by`, `created_at`) VALUES (:nama, :nilai, :deskripsi, :updated_at, :updated_by, :created_at). Bound with :nama='pembelian.pembulatankeatashj', :nilai='50', :deskripsi='Kelipatan pembulatan ke atas untuk harga jual pada input pembelian', :updated_at='now()', :updated_by=1, :created_at='now()' in /var/www/html/ap3/framework/db/CDbCommand.php:358

SOLUSI :

Cari string sbb :

        $this->insert('config', array('nama' => 'pembelian.pembulatankeatashj', 'nilai' => '50', 'deskripsi' => 'Kelipatan pembulatan ke atas untuk harga jual pada input pembelian', 'updated_at' => 'now()', 'updated_by' => 1, 'created_at' => 'now()'));

Ganti menjadi :

        $this->insert('config', array('nama' => 'pembelian.pembulatankeatashj', 'nilai' => '50', 'deskripsi' => 'Kelipatan pembulatan ke atas untuk harga jual pada input pembelian', 'updated_at' => date("Y-m-d H:i:s", time()), 'updated_by' => 1, 'created_at' => date("Y-m-d H:i:s", time())));

Terimakasih.

**Comment by AbuMuhammad** [comment]
[Selesai](https://github.com/AbuMuhammad/ap3/commit/63cd6e660a77f5b8818e863b3513b77362ed15f6)
